services:
  wordzle:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - "redis"
  client:
    build: ../client
    ports:
      - "3000:80"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx/
    ports:
      - "5000:5000"
