services:
  wordzle:
    build: .
    depends_on:
      - "redis"
#  client:
#    build: ../client/
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx/
    ports:
      - "5000:5000"
