spring:
  session:
    store-type: redis
  redis:
    host: localhost # set to host.docker.internal when building docker image.
    database: 0
    port: 6379
reset-word-task:
  url: "https://random-word-api.herokuapp.com/word"
  delay: 30000