spring:
  session:
    store-type: redis
  redis:
    host: localhost # set to 'redis' or 'host.docker.internal' when running as a container.
    database: 0
    port: 6379
reset-word-task:
  delay: 30000
