spring:
  session:
    store-type: redis
  redis:
    host: localhost # set to 'redis' when running as a container.
    database: 0
    port: 6379
reset-word-task:
  url: "https://random-word-api.herokuapp.com/word"
  delay: 100000
